### ISSUE TITLE
[NumberGuesser] Где файлы?

### ISSUE THREAD

**Issue by pavel-b-novikov** [sohich/nsudotnet#1]
csproj, папка Properties?

**Comment by sohich** [comment]
Добавил. Не осознал, что gitignore препятствует добавлению ненужных файлов, поэтому вручную добавил именно исходники и solution

**Comment by pavel-b-novikov** [comment]
То есть вы не умеете пользоваться gitignore?..
Ну.. как говорится - б-г простит
