### ISSUE TITLE
[NumberGuesser] LogRecord

### ISSUE THREAD

**Issue by pavel-b-novikov** [sohich/nsudotnet#3]
Get-методы? В C#? Да правда чтоли?

И приватные поля PascalCase-ом не называются

**Comment by pavel-b-novikov** [comment]
То же самое с LogStorage.

У меня ощущение что вы (думаете что) знаете java, и подумали что в C# все как с Java, разобрались за один вечер и что-то наляпали.

**Comment by sohich** [comment]
Исправил, теперь использую проперти. Сначала не очень уловил, что для автоматически объявленного property компилятор создает приватное анонимное поле, доступное только через это property

**Comment by pavel-b-novikov** [comment]
Другое дело
