### ISSUE TITLE
[NumberGuesser] "q".Equals(message)

### ISSUE THREAD

**Issue by pavel-b-novikov** [sohich/nsudotnet#4]
Почему вы пишете именно так?
Как правильно и почему?

**Comment by sohich** [comment]
Переделал с использованием ==. Отвык от перегрузки операторов.
Если операндами для == являются два string'a, то уже на этапе компиляции будет
понятно, что вызовется именно перегруженный метод (который, в свою очередь, вызовет String.Equals(string, string)) и сверка будет произведена на равенство значений, а не ссылок.

**Comment by pavel-b-novikov** [comment]
Я никак не могу понять почему вы все упоминаете этап компиляции и упираете на это? Как будто в Java на этапе компиляции неизвестно что это строки.

**Comment by pavel-b-novikov** [comment]
Но ладно
