### ISSUE TITLE
[Calendar] CheckWeekend

### ISSUE THREAD

**Issue by pavel-b-novikov** [sohich/nsudotnet#6]
Переделайте, пожалуйста, в extension-метод

**Comment by pavel-b-novikov** [comment]
Заодно и все методы, делающие действия на основе дня недели или даты

**Comment by sohich** [comment]
Сделал методы 
CheckWeekend(DayOfWeek), 
SetConsoleBackgroundByDay(DateTime),
SetConsoleForegroundByday(DayOfWeek)
методами расширения классов DayOfWeek и DateTime соответственно.
Вынес их в отдельный static class, туда же перенес константы, связанные с цветом консоли. 
Насколько я понял, написать extension-метод для консоли возможным не представляется, поэтому добавил в этот же класс пару обычных статических методов, чтобы выставлять цвет в консоли на дефолтные значения для календаря
